import { Project } from "@/types/project";

export const MOCK_PROJECTS: Project[] = [
  {
    id: "p1",
    slug: "lodha-luxuria-pune",
    name: "Lodha Luxuria",
    builderName: "Lodha Group",
    builderScore: 92,
    location: "Kharadi",
    city: "Pune",
    lat: 18.551,
    lng: 73.943,
    tagline: "Ultra-luxury living in the heart of East Pune",
    description: "Experience world-class amenities and unmatched luxury at Kharadi's most prestigious address.",
    trustScore: 88,
    riskLabel: "low",
    reraId: "P52100012345",
    reraExpiry: "2028-12-31",
    launchDate: "2023-01-01",
    possessionDate: "2027-06-30",
    totalUnits: 450,
    availableUnits: 120,
    unitConfigs: [
      {
        id: "u1",
        type: "2BHK",
        area: 1150,
        priceMin: 11500000,
        priceMax: 12500000,
        pricePerSqFt: 10000,
        available: 45,
        total: 150,
        floor: "High",
        facing: ["East", "Garden"],
        images: ["https://images.unsplash.com/photo-1460317442991-0ec239f3d6bd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Spacious balcony", "Smart home automation"]
      },
      {
        id: "u2",
        type: "3BHK",
        area: 1650,
        priceMin: 16500000,
        priceMax: 18500000,
        pricePerSqFt: 10000,
        available: 20,
        total: 100,
        floor: "Any",
        facing: ["West", "Clubhouse"],
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Walk-in wardrobe", "Premium marble flooring"]
      }
    ],
    pros: ["Premium builder reputation", "Walking distance to IT parks", "Advanced smart home features"],
    cons: ["Higher than average price per sqft", "Ongoing construction noise"],
    amenities: ["Olympic Pool", "Sky Lounge", "24/7 Concierge", "Private Theatre"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 45,
    isPublished: true
  },
  {
    id: "p2",
    slug: "godrej-infinity-pune",
    name: "Godrej Infinity",
    builderName: "Godrej Properties",
    builderScore: 95,
    location: "Keshav Nagar",
    city: "Pune",
    lat: 18.535,
    lng: 73.957,
    tagline: "Sustainable homes by the riverside",
    description: "Nestled along the Mula-Mutha river, Infinity offers a perfect blend of nature and modern living.",
    trustScore: 94,
    riskLabel: "low",
    reraId: "P52100054321",
    reraExpiry: "2026-06-30",
    launchDate: "2021-06-01",
    possessionDate: "2026-03-31",
    totalUnits: 800,
    availableUnits: 50,
    unitConfigs: [
      {
        id: "u3",
        type: "1BHK",
        area: 650,
        priceMin: 5500000,
        priceMax: 6000000,
        pricePerSqFt: 8461,
        available: 5,
        total: 200,
        floor: "Mid",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Compact design", "Excellent ventilation"]
      }
    ],
    pros: ["Strong builder brand", "Excellent appreciation potential", "Eco-friendly design"],
    cons: ["Narrow access roads", "Distance from metro line"],
    amenities: ["Riverwalk", "Organic Farm", "Sports Arena", "Yoga Deck"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 85,
    isPublished: true
  },
  {
    id: "p3",
    slug: "amanora-gateway-towers",
    name: "Amanora Gateway Towers",
    builderName: "Amanora Park Town",
    builderScore: 90,
    location: "Hadapsar",
    city: "Pune",
    lat: 18.518,
    lng: 73.935,
    tagline: "The tallest residential towers in Pune",
    description: "Live above the clouds in these Swarovski-branded residential towers at Amanora Park Town.",
    trustScore: 92,
    riskLabel: "low",
    reraId: "P52100000123",
    reraExpiry: "2025-12-31",
    launchDate: "2018-01-01",
    possessionDate: "2025-06-30",
    totalUnits: 320,
    availableUnits: 40,
    unitConfigs: [
      {
        id: "u4",
        type: "4BHK",
        area: 3500,
        priceMin: 45000000,
        priceMax: 55000000,
        pricePerSqFt: 12857,
        available: 5,
        total: 80,
        floor: "High",
        facing: ["Skyline"],
        images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Private plunge pool", "Swarovski interiors"]
      }
    ],
    pros: ["Iconic landmark", "Integrated township perks", "Unmatched views"],
    cons: ["Maintenance cost is high", "Traffic congestion at exit gates"],
    amenities: ["Rooftop Infinity Pool", "Digital Lounge", "Automated Parking"],
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p4",
    slug: "vascon-goodlife-talegaon",
    name: "Vascon Goodlife",
    builderName: "Vascon Engineers",
    builderScore: 85,
    location: "Talegaon",
    city: "Pune",
    lat: 18.730,
    lng: 73.676,
    tagline: "Smart budget homes for a better life",
    description: "Affordable housing focused on learning and development for children and young professionals.",
    trustScore: 82,
    riskLabel: "low",
    reraId: "P52100016543",
    reraExpiry: "2026-12-31",
    launchDate: "2022-03-01",
    possessionDate: "2026-12-31",
    totalUnits: 600,
    availableUnits: 250,
    unitConfigs: [
      {
        id: "u5",
        type: "1RK",
        area: 350,
        priceMin: 1800000,
        priceMax: 2200000,
        pricePerSqFt: 5142,
        available: 100,
        total: 150,
        floor: "Any",
        facing: ["East", "West"],
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Optimized space", "Low maintenance"]
      },
      {
        id: "u6",
        type: "1BHK",
        area: 550,
        priceMin: 2800000,
        priceMax: 3200000,
        pricePerSqFt: 5090,
        available: 80,
        total: 250,
        floor: "Mid",
        facing: ["Garden"],
        images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Balcony", "Utility area"]
      }
    ],
    pros: ["Extremely affordable", "Learning center within complex", "Good for industrial workers"],
    cons: ["Far from Pune city center", "Basic finishes"],
    amenities: ["Library", "Study Rooms", "Basketball Court", "Open Gym"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 35,
    isPublished: true
  },
  {
    id: "p5",
    slug: "kolte-patil-life-republic",
    name: "Life Republic",
    builderName: "Kolte Patil",
    builderScore: 88,
    location: "Hinjewadi",
    city: "Pune",
    lat: 18.591,
    lng: 73.719,
    tagline: "A 400-acre township of dreams",
    description: "A community designed for meaningful living, from studios to luxury villas.",
    trustScore: 90,
    riskLabel: "low",
    reraId: "P52100002145",
    reraExpiry: "2027-12-31",
    launchDate: "2015-01-01",
    possessionDate: "2027-12-31",
    totalUnits: 5000,
    availableUnits: 450,
    unitConfigs: [
      {
        id: "u7",
        type: "2BHK",
        area: 950,
        priceMin: 7500000,
        priceMax: 8500000,
        pricePerSqFt: 7894,
        available: 120,
        total: 1000,
        floor: "Any",
        facing: ["East", "West"],
        images: ["https://images.unsplash.com/photo-1460317442991-0ec239f3d6bd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Township access", "Dedicated parking"]
      }
    ],
    pros: ["Huge open spaces", "In-house school and hospital", "High rental demand"],
    cons: ["Construction is perpetual", "Internal travel is time-consuming"],
    amenities: ["Town Center", "Skating Rink", "Multi-speciality Hospital", "CBSE School"],
    images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 70,
    isPublished: true
  },
  {
    id: "p6",
    slug: "shapoorji-joyville-sensorium",
    name: "Joyville Sensorium",
    builderName: "Shapoorji Pallonji",
    builderScore: 94,
    location: "Hinjewadi Phase 1",
    city: "Pune",
    lat: 18.579,
    lng: 73.738,
    tagline: "Senses aligned, life defined",
    description: "Edge-certified smart homes near the IT hub with focus on wellness and technology.",
    trustScore: 93,
    riskLabel: "low",
    reraId: "P52100024963",
    reraExpiry: "2026-09-30",
    launchDate: "2020-10-01",
    possessionDate: "2026-06-30",
    totalUnits: 1100,
    availableUnits: 95,
    unitConfigs: [
      {
        id: "u8",
        type: "2BHK",
        area: 1050,
        priceMin: 9200000,
        priceMax: 10500000,
        pricePerSqFt: 8761,
        available: 30,
        total: 500,
        floor: "High",
        facing: ["Hills"],
        images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Voice controlled lights", "River views"]
      }
    ],
    pros: ["Trusted SP brand", "Zero walk to major IT offices", "Riverfront development"],
    cons: ["Peak hour traffic", "Premium pricing for Hinjewadi"],
    amenities: ["5D Miniplex", "Musical Fountain", "Sound Healing Room"],
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 60,
    isPublished: true
  },
  {
    id: "p7",
    slug: "puraniks-abitante-fiore",
    name: "Puraniks Abitante Fiore",
    builderName: "Puranik Builders",
    builderScore: 84,
    location: "Bavdhan",
    city: "Pune",
    lat: 18.514,
    lng: 73.771,
    tagline: "Nature-inspired Italian lifestyle",
    description: "Nestled in the lush hills of Bavdhan, Abitante Fiore brings Italian aesthetics to Pune.",
    trustScore: 81,
    riskLabel: "medium",
    reraId: "P52100018974",
    reraExpiry: "2027-03-31",
    launchDate: "2022-01-01",
    possessionDate: "2026-12-31",
    totalUnits: 550,
    availableUnits: 180,
    unitConfigs: [
      {
        id: "u9",
        type: "2.5BHK",
        area: 1350,
        priceMin: 10500000,
        priceMax: 11500000,
        pricePerSqFt: 7777,
        available: 40,
        total: 100,
        floor: "Mid",
        facing: ["Valley"],
        images: ["https://images.unsplash.com/photo-1480074568708-e7b720bb3f09?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Extra study room", "Private terrace"]
      }
    ],
    pros: ["Scenic hill views", "Fastest growing residential suburb", "Excellent air quality"],
    cons: ["Delay in previous phases", "Steep internal roads"],
    amenities: ["Vineyard Path", "Amphitheatre", "Infinity Pool"],
    images: ["https://images.unsplash.com/photo-1449156001437-3a16d1dfda70?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 40,
    isPublished: true
  },
  {
    id: "p8",
    slug: "vtp-cygnus-manjri",
    name: "VTP Cygnus",
    builderName: "VTP Realty",
    builderScore: 91,
    location: "Manjri",
    city: "Pune",
    lat: 18.512,
    lng: 73.982,
    tagline: "Premium smart homes in a massive township",
    description: "Part of the 100+ acre VTP Luxe cluster, Cygnus offers MLA (Maximum Liveable Area) homes.",
    trustScore: 89,
    riskLabel: "low",
    reraId: "P52100021547",
    reraExpiry: "2026-12-31",
    launchDate: "2021-01-01",
    possessionDate: "2026-06-30",
    totalUnits: 900,
    availableUnits: 110,
    unitConfigs: [
      {
        id: "u10",
        type: "2BHK",
        area: 850,
        priceMin: 6800000,
        priceMax: 7500000,
        pricePerSqFt: 8000,
        available: 50,
        total: 400,
        floor: "Any",
        facing: ["North", "East"],
        images: ["https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&q=80&w=800"],
        highlights: ["No space wastage", "Large windows"]
      }
    ],
    pros: ["Exceptional layout design", "Rapid infrastructure growth", "VTP delivery track record"],
    cons: ["Near railway line (noise)", "Internal roads still developing"],
    amenities: ["Huge Clubhouse", "Cricket Ground", "Work from Home zone"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 55,
    isPublished: true
  },
  {
    id: "p9",
    slug: "pride-world-city-charholi",
    name: "Pride World City",
    builderName: "Pride Group",
    builderScore: 86,
    location: "Charholi",
    city: "Pune",
    lat: 18.641,
    lng: 73.897,
    tagline: "A global city for a global lifestyle",
    description: "A 400-acre mega project close to Pune Airport, offering a self-sustained ecosystem.",
    trustScore: 85,
    riskLabel: "low",
    reraId: "P52100001548",
    reraExpiry: "2028-12-31",
    launchDate: "2014-01-01",
    possessionDate: "2027-12-31",
    totalUnits: 4000,
    availableUnits: 300,
    unitConfigs: [
      {
        id: "u11",
        type: "3BHK Villa",
        area: 2200,
        priceMin: 22000000,
        priceMax: 26000000,
        pricePerSqFt: 10000,
        available: 15,
        total: 100,
        floor: "G+1",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Private garden", "Double height ceiling"]
      }
    ],
    pros: ["Proximity to Airport", "Wide roads and infrastructure", "High capital appreciation"],
    cons: ["Slightly secluded", "High utility charges"],
    amenities: ["Artificial Lake", "Marina", "Shopping Mall", "Bus Terminus"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 65,
    isPublished: true
  },
  {
    id: "p10",
    slug: "kasturi-the-balmoral-riverside",
    name: "The Balmoral Riverside",
    builderName: "Kasturi Builders",
    builderScore: 96,
    location: "Balewadi",
    city: "Pune",
    lat: 18.563,
    lng: 73.774,
    tagline: "Architecture that inspires",
    description: "Award-winning ultra-luxury apartments with the best design standards in the industry.",
    trustScore: 95,
    riskLabel: "low",
    reraId: "P52100022365",
    reraExpiry: "2025-06-30",
    launchDate: "2021-06-01",
    possessionDate: "2025-03-31",
    totalUnits: 120,
    availableUnits: 15,
    unitConfigs: [
      {
        id: "u12",
        type: "4.5BHK",
        area: 3800,
        priceMin: 55000000,
        priceMax: 65000000,
        pricePerSqFt: 14473,
        available: 4,
        total: 40,
        floor: "Any",
        facing: ["River", "Hills"],
        images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Designer kitchen", "Full height windows"]
      }
    ],
    pros: ["Best design in Pune", "Extremely high build quality", "Prestigious Balewadi address"],
    cons: ["Very high entry price", "No smaller configurations"],
    amenities: ["Art Gallery", "Heated Pool", "Smart Parking"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p11",
    slug: "kohinoor-presidia-pimple-saudagar",
    name: "Kohinoor Presidia",
    builderName: "Kohinoor Group",
    builderScore: 89,
    location: "Pimple Saudagar",
    city: "Pune",
    lat: 18.594,
    lng: 73.791,
    tagline: "Sada Sukhi Raho at the best location",
    description: "Premium residences in the most sought-after family-friendly residential hub of PCMC.",
    trustScore: 91,
    riskLabel: "low",
    reraId: "P52100028741",
    reraExpiry: "2026-12-31",
    launchDate: "2022-06-01",
    possessionDate: "2026-12-31",
    totalUnits: 250,
    availableUnits: 65,
    unitConfigs: [
      {
        id: "u13",
        type: "3BHK",
        area: 1450,
        priceMin: 14500000,
        priceMax: 16500000,
        pricePerSqFt: 10000,
        available: 25,
        total: 100,
        floor: "Mid",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Spacious master suite", "Cross ventilation"]
      }
    ],
    pros: ["Prime established location", "Reputed delivery track record", "Excellent rental yields"],
    cons: ["Limited open space", "Traffic in Pimple Saudagar"],
    amenities: ["Grand Entrance Plaza", "Mini Theatre", "Kids Play Area"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 50,
    isPublished: true
  },
  {
    id: "p12",
    slug: "shree-villas-plots-undri",
    name: "Shree Villas & Plots",
    builderName: "Shree Developers",
    builderScore: 78,
    location: "Undri",
    city: "Pune",
    lat: 18.455,
    lng: 73.918,
    tagline: "Build your dream home on your own land",
    description: "Gated community of NA plots and custom villas in the greenery of South Pune.",
    trustScore: 75,
    riskLabel: "high",
    reraId: "P52100015964",
    reraExpiry: "2025-12-31",
    launchDate: "2022-01-01",
    possessionDate: "2025-01-01",
    totalUnits: 50,
    availableUnits: 12,
    unitConfigs: [
      {
        id: "u14",
        type: "Plot",
        area: 2500,
        priceMin: 4500000,
        priceMax: 5500000,
        pricePerSqFt: 1800,
        available: 8,
        total: 40,
        floor: "N/A",
        facing: ["East", "West"],
        images: ["https://images.unsplash.com/photo-1500382017468-9049fee74a62?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Immediate registration", "Clear title"]
      }
    ],
    pros: ["Land ownership", "Peaceful locality", "Low entry cost for land"],
    cons: ["Water scarcity in Undri", "Slow development of approach roads"],
    amenities: ["Gated Perimeter", "LED Streetlights", "Fruit Orchard"],
    images: ["https://images.unsplash.com/photo-1500382017468-9049fee74a62?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p13",
    slug: "nyati-elysia-kharadi",
    name: "Nyati Elysia",
    builderName: "Nyati Group",
    builderScore: 93,
    location: "Kharadi",
    city: "Pune",
    lat: 18.547,
    lng: 73.938,
    tagline: "A majestic landmark at Kharadi",
    description: "Modern apartments overlooking the river, built with Nyati's trademark quality.",
    trustScore: 92,
    riskLabel: "low",
    reraId: "P52100000742",
    reraExpiry: "2024-12-31",
    launchDate: "2019-01-01",
    possessionDate: "2024-06-30",
    totalUnits: 300,
    availableUnits: 20,
    unitConfigs: [
      {
        id: "u15",
        type: "2BHK",
        area: 1250,
        priceMin: 12000000,
        priceMax: 13500000,
        pricePerSqFt: 9600,
        available: 10,
        total: 150,
        floor: "Mid",
        facing: ["River"],
        images: ["https://images.unsplash.com/photo-1460317442991-0ec239f3d6bd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Huge balcony", "Branded fittings"]
      }
    ],
    pros: ["Very high build quality", "Zero maintenance issues", "Excellent location"],
    cons: ["Slightly dated design compared to newcomers", "Pricey maintenance"],
    amenities: ["Swimming Pool", "Gym", "Landscaped Garden"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p14",
    slug: "kumar-prospera-hadapsar",
    name: "Kumar Prospera",
    builderName: "Kumar Properties",
    builderScore: 90,
    location: "Hadapsar",
    city: "Pune",
    lat: 18.508,
    lng: 73.927,
    tagline: "Prosperous living in East Pune",
    description: "Centrally located near Magarpatta and Amanora, Prospera is designed for families.",
    trustScore: 91,
    riskLabel: "low",
    reraId: "P52100014785",
    reraExpiry: "2026-06-30",
    launchDate: "2021-01-01",
    possessionDate: "2026-01-01",
    totalUnits: 400,
    availableUnits: 45,
    unitConfigs: [
      {
        id: "u16",
        type: "3BHK",
        area: 1550,
        priceMin: 15500000,
        priceMax: 17500000,
        pricePerSqFt: 10000,
        available: 12,
        total: 150,
        floor: "Any",
        facing: ["Clubhouse"],
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Corner apartment", "3 balconies"]
      }
    ],
    pros: ["Central connectivity", "Strong resale value", "Reliable builder"],
    cons: ["Crowded neighbourhood", "Basic amenities"],
    amenities: ["Clubhouse", "Children Play Area", "Senior Citizen Park"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 75,
    isPublished: true
  },
  {
    id: "p15",
    slug: "mantra-mirage-mundhwa",
    name: "Mantra Mirage",
    builderName: "Mantra Properties",
    builderScore: 82,
    location: "Mundhwa",
    city: "Pune",
    lat: 18.531,
    lng: 73.925,
    tagline: "Smarter homes, better locations",
    description: "Compact 2 and 3 BHK homes in the heart of the Golden Triangle (Kharadi-Hadapsar-Mundhwa).",
    trustScore: 79,
    riskLabel: "medium",
    reraId: "P52100019654",
    reraExpiry: "2027-12-31",
    launchDate: "2023-01-01",
    possessionDate: "2027-12-31",
    totalUnits: 650,
    availableUnits: 280,
    unitConfigs: [
      {
        id: "u17",
        type: "2BHK",
        area: 780,
        priceMin: 7200000,
        priceMax: 7800000,
        pricePerSqFt: 9230,
        available: 150,
        total: 400,
        floor: "Any",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Compact layout", "Modern aesthetics"]
      }
    ],
    pros: ["High potential for IT rentals", "Compact and efficient", "Competitive pricing"],
    cons: ["Narrow lane for access", "Nearby slums in some patches"],
    amenities: ["Rooftop Yoga", "Co-working Space", "EV Charging Station"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 20,
    isPublished: true
  },
  {
    id: "p16",
    slug: "gera-world-of-joy-kharadi",
    name: "Gera World of Joy",
    builderName: "Gera Developments",
    builderScore: 95,
    location: "Kharadi",
    city: "Pune",
    lat: 18.558,
    lng: 73.948,
    tagline: "Let your kids outgrow their childhood",
    description: "Child-centric homes with expert training for sports and arts inside the campus.",
    trustScore: 94,
    riskLabel: "low",
    reraId: "P52100022471",
    reraExpiry: "2026-06-30",
    launchDate: "2020-01-01",
    possessionDate: "2025-12-31",
    totalUnits: 1200,
    availableUnits: 85,
    unitConfigs: [
      {
        id: "u18",
        type: "Duplex 3BHK",
        area: 1950,
        priceMin: 21000000,
        priceMax: 24000000,
        pricePerSqFt: 10769,
        available: 10,
        total: 50,
        floor: "High",
        facing: ["Amenity Space"],
        images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Double height living", "Kid-safe design"]
      }
    ],
    pros: ["Unmatched child-centric features", "5-year warranty on homes", "High-end coaching included"],
    cons: ["Very large project (crowded)", "High traffic entry point"],
    amenities: ["Badminton Academy", "Swimming Academy", "Dance Studio", "Martial Arts"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 80,
    isPublished: true
  },
  {
    id: "p17",
    slug: "supreme-estia-baner",
    name: "Supreme Estia",
    builderName: "Supreme Universal",
    builderScore: 94,
    location: "Baner",
    city: "Pune",
    lat: 18.568,
    lng: 73.784,
    tagline: "The gold standard of Baner",
    description: "Exquisite 2, 3, and 4 BHK homes in the most premium sector of Baner.",
    trustScore: 93,
    riskLabel: "low",
    reraId: "P52100021487",
    reraExpiry: "2026-12-31",
    launchDate: "2021-01-01",
    possessionDate: "2026-06-30",
    totalUnits: 450,
    availableUnits: 40,
    unitConfigs: [
      {
        id: "u19",
        type: "4BHK",
        area: 2800,
        priceMin: 38000000,
        priceMax: 45000000,
        pricePerSqFt: 13571,
        available: 5,
        total: 40,
        floor: "High",
        facing: ["East", "City View"],
        images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Italian Marble", "Automation Ready"]
      }
    ],
    pros: ["Supreme's premium finish", "Excellent layout efficiency", "Quiet residential pocket"],
    cons: ["Premium price point", "Limited visitor parking"],
    amenities: ["Sky Spa", "Artisanal Garden", "Smart Concierge"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 65,
    isPublished: true
  },
  {
    id: "p18",
    slug: "goel-ganga-serenity-undri",
    name: "Ganga Serenity",
    builderName: "Goel Ganga Developments",
    builderScore: 82,
    location: "Undri",
    city: "Pune",
    lat: 18.459,
    lng: 73.912,
    tagline: "A serene lifestyle in the hills",
    description: "Quiet and peaceful apartments for those who want to escape the city noise.",
    trustScore: 80,
    riskLabel: "medium",
    reraId: "P52100016578",
    reraExpiry: "2027-06-30",
    launchDate: "2022-01-01",
    possessionDate: "2027-03-31",
    totalUnits: 350,
    availableUnits: 120,
    unitConfigs: [
      {
        id: "u20",
        type: "2BHK",
        area: 1050,
        priceMin: 5800000,
        priceMax: 6500000,
        pricePerSqFt: 5523,
        available: 40,
        total: 150,
        floor: "Mid",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Open views", "Low pollution area"]
      }
    ],
    pros: ["Very quiet environment", "Value for money", "Spacious layouts"],
    cons: ["Distance from workplace", "Developing infrastructure"],
    amenities: ["Hill Trail", "Open Gym", "Meditation Deck"],
    images: ["https://images.unsplash.com/photo-1449156001437-3a16d1dfda70?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 40,
    isPublished: true
  },
  {
    id: "p19",
    slug: "pride-purple-park-connect-hinjewadi",
    name: "Park Connect",
    builderName: "Pride Purple",
    builderScore: 92,
    location: "Hinjewadi Phase 2",
    city: "Pune",
    lat: 18.598,
    lng: 73.705,
    tagline: "Connected to work, connected to life",
    description: "Compact premium homes for the modern IT professional with no wastage of space.",
    trustScore: 91,
    riskLabel: "low",
    reraId: "P52100025641",
    reraExpiry: "2026-03-31",
    launchDate: "2021-06-01",
    possessionDate: "2025-12-31",
    totalUnits: 850,
    availableUnits: 45,
    unitConfigs: [
      {
        id: "u21",
        type: "2BHK",
        area: 750,
        priceMin: 7800000,
        priceMax: 8200000,
        pricePerSqFt: 10400,
        available: 20,
        total: 400,
        floor: "Any",
        facing: ["West"],
        images: ["https://images.unsplash.com/photo-1460317442991-0ec239f3d6bd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Zero wastage plan", "Smart locks"]
      }
    ],
    pros: ["Walking distance to Tech Mahindra", "Pride Purple reliability", "Excellent for investment"],
    cons: ["Small carpet area", "Busy IT corridor"],
    amenities: ["Co-working Pods", "Indoor Games", "Mini Library"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 85,
    isPublished: true
  },
  {
    id: "p20",
    slug: "kalpataru-jade-residences-baner",
    name: "Kalpataru Jade Residences",
    builderName: "Kalpataru",
    builderScore: 93,
    location: "Baner-Sus",
    city: "Pune",
    lat: 18.552,
    lng: 73.764,
    tagline: "Luxury by the hills",
    description: "Premium large-sized apartments tucked away in a quiet corner of Baner hills.",
    trustScore: 92,
    riskLabel: "low",
    reraId: "P52100000456",
    reraExpiry: "2025-12-31",
    launchDate: "2018-01-01",
    possessionDate: "2025-06-30",
    totalUnits: 350,
    availableUnits: 30,
    unitConfigs: [
      {
        id: "u22",
        type: "3BHK",
        area: 1850,
        priceMin: 22500000,
        priceMax: 26500000,
        pricePerSqFt: 12162,
        available: 12,
        total: 100,
        floor: "High",
        facing: ["Hills"],
        images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Extra large deck", "Servant room"]
      }
    ],
    pros: ["Scenic hill view", "Premium brand value", "Excellent air quality"],
    cons: ["Approach road is narrow", "No small configurations"],
    amenities: ["Hill Walk", "Forest Lounge", "Spa & Sauna"],
    images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 90,
    isPublished: true
  },
  {
    id: "p21",
    slug: "majestic-towers-wagholi",
    name: "Majestic Towers",
    builderName: "Majestic Landmarks",
    builderScore: 76,
    location: "Wagholi",
    city: "Pune",
    lat: 18.581,
    lng: 73.978,
    tagline: "Affordable luxury for young families",
    description: "Budget-friendly 2BHK apartments in the growing eastern suburb of Wagholi.",
    trustScore: 72,
    riskLabel: "medium",
    reraId: "P52100024158",
    reraExpiry: "2026-12-31",
    launchDate: "2022-01-01",
    possessionDate: "2026-12-31",
    totalUnits: 400,
    availableUnits: 150,
    unitConfigs: [
      {
        id: "u23",
        type: "2BHK",
        area: 950,
        priceMin: 4800000,
        priceMax: 5500000,
        pricePerSqFt: 5052,
        available: 80,
        total: 200,
        floor: "Any",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
        highlights: ["In-house shop", "Kids area"]
      }
    ],
    pros: ["Very affordable", "Fast appreciation", "Good school nearby"],
    cons: ["Water scarcity", "Heavy traffic on Pune-Ahmednagar road"],
    amenities: ["Kids Pool", "Party Lawn", "Gym"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 30,
    isPublished: true
  },
  {
    id: "p22",
    slug: "vtp-verve-baner",
    name: "VTP Verve",
    builderName: "VTP Realty",
    builderScore: 91,
    location: "Baner",
    city: "Pune",
    lat: 18.575,
    lng: 73.785,
    tagline: "Ultra-modern homes in Baner-Next",
    description: "Smartly designed apartments with automation and high-end specifications.",
    trustScore: 89,
    riskLabel: "low",
    reraId: "P52100028954",
    reraExpiry: "2027-06-30",
    launchDate: "2022-06-01",
    possessionDate: "2027-03-31",
    totalUnits: 300,
    availableUnits: 85,
    unitConfigs: [
      {
        id: "u24",
        type: "3BHK",
        area: 1350,
        priceMin: 14500000,
        priceMax: 16500000,
        pricePerSqFt: 10740,
        available: 30,
        total: 100,
        floor: "Mid",
        facing: ["Amenity Space"],
        images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Smart automation", "Premium bath fittings"]
      }
    ],
    pros: ["Excellent layout design", "Rapidly developing area", "VTP brand trust"],
    cons: ["Under construction dust", "Pricey for area"],
    amenities: ["Clubhouse", "Infinity Pool", "Yoga Deck"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 25,
    isPublished: true
  },
  {
    id: "p23",
    slug: "paranjape-schemes-blue-ridge-hinjewadi",
    name: "Blue Ridge",
    builderName: "Paranjape Schemes",
    builderScore: 92,
    location: "Hinjewadi Phase 1",
    city: "Pune",
    lat: 18.581,
    lng: 73.731,
    tagline: "The gold standard of township living",
    description: "An iconic 138-acre township that changed the face of Hinjewadi.",
    trustScore: 94,
    riskLabel: "low",
    reraId: "P52100000147",
    reraExpiry: "2024-12-31",
    launchDate: "2010-01-01",
    possessionDate: "2024-06-30",
    totalUnits: 4000,
    availableUnits: 15,
    unitConfigs: [
      {
        id: "u25",
        type: "2BHK",
        area: 1100,
        priceMin: 10500000,
        priceMax: 11500000,
        pricePerSqFt: 9545,
        available: 5,
        total: 100,
        floor: "High",
        facing: ["Golf Course"],
        images: ["https://images.unsplash.com/photo-1460317442991-0ec239f3d6bd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Golf course view", "Township perks"]
      }
    ],
    pros: ["Self-contained township", "Golf course inside", "Reputed builder"],
    cons: ["Very old project (some towers)", "High maintenance"],
    amenities: ["Golf Course", "School", "Mall", "Bus Hub"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p24",
    slug: "oxford-florida-river-estate-mundhwa",
    name: "Florida River Estate",
    builderName: "Oxford Group",
    builderScore: 84,
    location: "Mundhwa",
    city: "Pune",
    lat: 18.538,
    lng: 73.918,
    tagline: "Riverside luxury at Mundhwa",
    description: "Spacious apartments with massive decks overlooking the Mula-Mutha river.",
    trustScore: 82,
    riskLabel: "medium",
    reraId: "P52100017425",
    reraExpiry: "2026-12-31",
    launchDate: "2021-01-01",
    possessionDate: "2026-06-30",
    totalUnits: 200,
    availableUnits: 35,
    unitConfigs: [
      {
        id: "u26",
        type: "3BHK",
        area: 1650,
        priceMin: 18500000,
        priceMax: 21500000,
        pricePerSqFt: 11212,
        available: 10,
        total: 60,
        floor: "High",
        facing: ["River"],
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"],
        highlights: ["10ft wide deck", "Direct river access"]
      }
    ],
    pros: ["Permanent river view", "Boutique development", "Quiet location"],
    cons: ["Slow execution", "No small configurations"],
    amenities: ["Riverside Boardwalk", "Private Garden", "Luxury Lounge"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 60,
    isPublished: true
  },
  {
    id: "p25",
    slug: "godrej-rejuve-keshav-nagar",
    name: "Godrej Rejuve",
    builderName: "Godrej Properties",
    builderScore: 95,
    location: "Keshav Nagar",
    city: "Pune",
    lat: 18.532,
    lng: 73.962,
    tagline: "Healthy living for a healthy you",
    description: "Focus on wellness with 2-acre greens and dedicated zones for physical health.",
    trustScore: 93,
    riskLabel: "low",
    reraId: "P52100020147",
    reraExpiry: "2025-12-31",
    launchDate: "2019-06-01",
    possessionDate: "2025-03-31",
    totalUnits: 750,
    availableUnits: 40,
    unitConfigs: [
      {
        id: "u27",
        type: "2BHK",
        area: 1050,
        priceMin: 8800000,
        priceMax: 9500000,
        pricePerSqFt: 8380,
        available: 15,
        total: 400,
        floor: "Mid",
        facing: ["Garden"],
        images: ["https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Wellness features", "Large windows"]
      }
    ],
    pros: ["Wellness focus", "Trusted brand", "High rental demand"],
    cons: ["Developing approach road", "Keshav Nagar traffic"],
    amenities: ["Pharmacy", "Health Cafe", "Boxing Ring", "Cycling Track"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 90,
    isPublished: true
  },
  {
    id: "p26",
    slug: "shree-samarth-plots-ravet",
    name: "Samarth Plots Ravet",
    builderName: "Samarth Developers",
    builderScore: 72,
    location: "Ravet",
    city: "Pune",
    lat: 18.648,
    lng: 73.748,
    tagline: "Prime residential plots near Express-way",
    description: "Small pocket of NA plots for those wanting to build their own homes in PCMC.",
    trustScore: 68,
    riskLabel: "high",
    reraId: "P52100028745",
    reraExpiry: "2025-06-30",
    launchDate: "2023-01-01",
    possessionDate: "2025-03-31",
    totalUnits: 30,
    availableUnits: 10,
    unitConfigs: [
      {
        id: "u28",
        type: "Plot",
        area: 1500,
        priceMin: 3500000,
        priceMax: 4200000,
        pricePerSqFt: 2333,
        available: 6,
        total: 30,
        floor: "N/A",
        facing: ["West"],
        images: ["https://images.unsplash.com/photo-1500382017468-9049fee74a62?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Near Expressway", "Clear title"]
      }
    ],
    pros: ["Investment potential", "Connectivity to Mumbai", "Gated community"],
    cons: ["Small developer", "Limited amenities", "Construction risk"],
    amenities: ["Concrete Roads", "Security Cabin", "Plantation"],
    images: ["https://images.unsplash.com/photo-1500382017468-9049fee74a62?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 40,
    isPublished: true
  },
  {
    id: "p27",
    slug: "yashwin-encore-wakad",
    name: "Yashwin Encore",
    builderName: "Vilshanti Developers",
    builderScore: 85,
    location: "Wakad",
    city: "Pune",
    lat: 18.595,
    lng: 73.765,
    tagline: "Smart lifestyle in the heart of Wakad",
    description: "Part of the successful Yashwin series, Encore offers functional 2 and 3 BHK homes.",
    trustScore: 88,
    riskLabel: "low",
    reraId: "P52100014758",
    reraExpiry: "2026-03-31",
    launchDate: "2021-01-01",
    possessionDate: "2025-12-31",
    totalUnits: 450,
    availableUnits: 60,
    unitConfigs: [
      {
        id: "u29",
        type: "2BHK",
        area: 820,
        priceMin: 8500000,
        priceMax: 9200000,
        pricePerSqFt: 10365,
        available: 25,
        total: 200,
        floor: "Mid",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Functional layout", "Near shopping mall"]
      }
    ],
    pros: ["Prime Wakad location", "Proven design", "Good maintenance history"],
    cons: ["Crowded access roads", "Noise from nearby highway"],
    amenities: ["Rooftop Cafe", "Mini Gym", "Library"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 80,
    isPublished: true
  },
  {
    id: "p28",
    slug: "manhattan-towers-baner",
    name: "Manhattan Towers",
    builderName: "Real Estate Inc",
    builderScore: 80,
    location: "Baner",
    city: "Pune",
    lat: 18.571,
    lng: 73.781,
    tagline: "New York style living in Pune",
    description: "Compact luxury with focus on amenities and community for young professionals.",
    trustScore: 78,
    riskLabel: "medium",
    reraId: "P52100028956",
    reraExpiry: "2028-12-31",
    launchDate: "2023-06-01",
    possessionDate: "2028-06-30",
    totalUnits: 250,
    availableUnits: 180,
    unitConfigs: [
      {
        id: "u30",
        type: "1BHK",
        area: 550,
        priceMin: 6500000,
        priceMax: 7200000,
        pricePerSqFt: 11818,
        available: 100,
        total: 150,
        floor: "High",
        facing: ["Skyline"],
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Fully furnished option", "Automation"]
      }
    ],
    pros: ["Niche product for bachelors", "High rental potential", "Premium amenities"],
    cons: ["Very high per sqft price", "Small unit size"],
    amenities: ["Sky Bar", "Digital Concierge", "Shared Workspace"],
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 10,
    isPublished: true
  },
  {
    id: "p29",
    slug: "kunal-aspiree-balewadi",
    name: "Kunal Aspiree",
    builderName: "Kunal Group",
    builderScore: 88,
    location: "Balewadi",
    city: "Pune",
    lat: 18.561,
    lng: 73.771,
    tagline: "Life at the top",
    description: "Established project in Balewadi with large open spaces and active community.",
    trustScore: 90,
    riskLabel: "low",
    reraId: "P52100000458",
    reraExpiry: "2024-12-31",
    launchDate: "2015-01-01",
    possessionDate: "2024-03-31",
    totalUnits: 500,
    availableUnits: 10,
    unitConfigs: [
      {
        id: "u31",
        type: "3BHK",
        area: 1450,
        priceMin: 16500000,
        priceMax: 18500000,
        pricePerSqFt: 11379,
        available: 3,
        total: 100,
        floor: "Mid",
        facing: ["Pool"],
        images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Spacious rooms", "Modern kitchen"]
      }
    ],
    pros: ["Ready to move", "Active social life", "Prime Balewadi location"],
    cons: ["No fresh inventory", "Resale prices are high"],
    amenities: ["Cricket Ground", "Banquet Hall", "Tennis Court"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p30",
    slug: "viva-sarovar-bavdhan",
    name: "Viva Sarovar",
    builderName: "Viva Developers",
    builderScore: 82,
    location: "Bavdhan",
    city: "Pune",
    lat: 18.518,
    lng: 73.768,
    tagline: "Boutique living near Pashan lake",
    description: "Quiet homes with views of Pashan lake and lush greenery around.",
    trustScore: 81,
    riskLabel: "low",
    reraId: "P52100018742",
    reraExpiry: "2026-12-31",
    launchDate: "2021-01-01",
    possessionDate: "2026-06-30",
    totalUnits: 150,
    availableUnits: 25,
    unitConfigs: [
      {
        id: "u32",
        type: "2BHK",
        area: 1000,
        priceMin: 8500000,
        priceMax: 9500000,
        pricePerSqFt: 8500,
        available: 12,
        total: 60,
        floor: "High",
        facing: ["Lake"],
        images: ["https://images.unsplash.com/photo-1449156001437-3a16d1dfda70?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Lake view", "Quiet neighborhood"]
      }
    ],
    pros: ["Peaceful surroundings", "Limited supply area", "Good resale value"],
    cons: ["Small project amenities", "Steep access road"],
    amenities: ["Terrace Garden", "Yoga Room", "EV Charging"],
    images: ["https://images.unsplash.com/photo-1449156001437-3a16d1dfda70?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 70,
    isPublished: true
  },
  {
    id: "p31",
    slug: "mantra-insignia-mundhwa",
    name: "Mantra Insignia",
    builderName: "Mantra Properties",
    builderScore: 82,
    location: "Mundhwa",
    city: "Pune",
    lat: 18.535,
    lng: 73.915,
    tagline: "Your hallmark of premium living",
    description: "Premium large-sized configurations in the heart of East Pune's IT belt.",
    trustScore: 78,
    riskLabel: "medium",
    reraId: "P52100021458",
    reraExpiry: "2027-12-31",
    launchDate: "2022-01-01",
    possessionDate: "2027-06-30",
    totalUnits: 450,
    availableUnits: 120,
    unitConfigs: [
      {
        id: "u33",
        type: "3BHK",
        area: 1450,
        priceMin: 13500000,
        priceMax: 15500000,
        pricePerSqFt: 9310,
        available: 40,
        total: 100,
        floor: "Mid",
        facing: ["Amenity Space"],
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Premium fixtures", "Spacious foyer"]
      }
    ],
    pros: ["Excellent location for IT workers", "Spacious layouts", "Good price point"],
    cons: ["Mantra execution track record", "Noise from nearby railway"],
    amenities: ["Party Hall", "Infinity Edge Pool", "Modern Gym"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 35,
    isPublished: true
  },
  {
    id: "p32",
    slug: "shree-villas-lonavala",
    name: "Shree Villas Lonavala",
    builderName: "Shree Developers",
    builderScore: 78,
    location: "Lonavala",
    city: "Pune",
    lat: 18.748,
    lng: 73.407,
    tagline: "Your second home in the clouds",
    description: "Luxury vacation villas with private pools and breathtaking mountain views.",
    trustScore: 74,
    riskLabel: "medium",
    reraId: "P52100024159",
    reraExpiry: "2026-12-31",
    launchDate: "2022-06-01",
    possessionDate: "2026-12-31",
    totalUnits: 25,
    availableUnits: 10,
    unitConfigs: [
      {
        id: "u34",
        type: "4BHK Villa",
        area: 3200,
        priceMin: 45000000,
        priceMax: 65000000,
        pricePerSqFt: 14062,
        available: 6,
        total: 25,
        floor: "G+2",
        facing: ["Mountains"],
        images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Private Pool", "Sky Deck"]
      }
    ],
    pros: ["Ideal vacation home", "Great ROI on weekend rentals", "Cooler climate"],
    cons: ["High maintenance", "Distance from Pune city", "Monsoon moisture issues"],
    amenities: ["Private Pool", "Barbecue Zone", "Clubhouse"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 45,
    isPublished: true
  },
  {
    id: "p33",
    slug: "amanora-sweet-water-villas",
    name: "Sweet Water Villas",
    builderName: "Amanora Park Town",
    builderScore: 90,
    location: "Hadapsar",
    city: "Pune",
    lat: 18.521,
    lng: 73.932,
    tagline: "Eco-friendly luxury villas",
    description: "Pune's most exclusive eco-friendly villa community with massive private plots.",
    trustScore: 92,
    riskLabel: "low",
    reraId: "P52100000148",
    reraExpiry: "2024-12-31",
    launchDate: "2012-01-01",
    possessionDate: "2024-03-31",
    totalUnits: 150,
    availableUnits: 5,
    unitConfigs: [
      {
        id: "u35",
        type: "5BHK Villa",
        area: 5500,
        priceMin: 120000000,
        priceMax: 150000000,
        pricePerSqFt: 21818,
        available: 2,
        total: 150,
        floor: "G+2",
        facing: ["Lake", "East"],
        images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Private Lakefront", "Eco-architecture"]
      }
    ],
    pros: ["Highest prestige in Pune", "Township infrastructure", "Massive land size"],
    cons: ["Extremely expensive", "Limited privacy from high-rises"],
    amenities: ["Private Lake", "Organic Farm", "Exclusive Club"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p34",
    slug: "kolte-patil-western-avenue-wakad",
    name: "Western Avenue",
    builderName: "Kolte Patil",
    builderScore: 88,
    location: "Wakad",
    city: "Pune",
    lat: 18.591,
    lng: 73.755,
    tagline: "Commercial and residential excellence",
    description: "Mixed-use development with high-street retail and premium residences in Wakad.",
    trustScore: 90,
    riskLabel: "low",
    reraId: "P52100000963",
    reraExpiry: "2024-06-30",
    launchDate: "2016-01-01",
    possessionDate: "2024-03-31",
    totalUnits: 600,
    availableUnits: 12,
    unitConfigs: [
      {
        id: "u36",
        type: "2BHK",
        area: 1100,
        priceMin: 9500000,
        priceMax: 10500000,
        pricePerSqFt: 8636,
        available: 5,
        total: 300,
        floor: "Mid",
        facing: ["City"],
        images: ["https://images.unsplash.com/photo-1460317442991-0ec239f3d6bd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["High-street view", "Modern layout"]
      }
    ],
    pros: ["Retail at doorstep", "Prime location", "Strong resale value"],
    cons: ["Noisy due to commercial activity", "Busy parking area"],
    amenities: ["High-street Retail", "Gym", "Landscaped Terrace"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p35",
    slug: "pride-purple-park-titanium-wakad",
    name: "Park Titanium",
    builderName: "Pride Purple",
    builderScore: 92,
    location: "Wakad",
    city: "Pune",
    lat: 18.598,
    lng: 73.768,
    tagline: "The pinnacle of Wakad living",
    description: "Large 3 and 4 BHK premium apartments for established families.",
    trustScore: 93,
    riskLabel: "low",
    reraId: "P52100018745",
    reraExpiry: "2025-12-31",
    launchDate: "2018-01-01",
    possessionDate: "2025-06-30",
    totalUnits: 250,
    availableUnits: 25,
    unitConfigs: [
      {
        id: "u37",
        type: "4BHK",
        area: 2400,
        priceMin: 28000000,
        priceMax: 35000000,
        pricePerSqFt: 11666,
        available: 8,
        total: 50,
        floor: "High",
        facing: ["Skyline"],
        images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Premium finish", "Large living room"]
      }
    ],
    pros: ["Best tower in Park District", "Large open spaces", "Established community"],
    cons: ["Very high maintenance", "No smaller units"],
    amenities: ["Olympics size pool", "Grand Lounge", "Sports Hub"],
    images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 95,
    isPublished: true
  },
  {
    id: "p36",
    slug: "godrej-rivergreens-manjri",
    name: "Godrej Rivergreens",
    builderName: "Godrej Properties",
    builderScore: 95,
    location: "Manjri",
    city: "Pune",
    lat: 18.515,
    lng: 73.985,
    tagline: "Live the township life",
    description: "Part of a 40-acre township with a massive clubhouse and riverfront greens.",
    trustScore: 94,
    riskLabel: "low",
    reraId: "P52100021456",
    reraExpiry: "2027-12-31",
    launchDate: "2022-01-01",
    possessionDate: "2027-06-30",
    totalUnits: 1200,
    availableUnits: 350,
    unitConfigs: [
      {
        id: "u38",
        type: "2BHK",
        area: 850,
        priceMin: 7200000,
        priceMax: 8200000,
        pricePerSqFt: 8470,
        available: 150,
        total: 500,
        floor: "Any",
        facing: ["Amenity Space"],
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Township perks", "Efficient layout"]
      }
    ],
    pros: ["Massive open space", "Godrej brand", "Future infrastructure growth"],
    cons: ["Distance from city center", "Under construction noise"],
    amenities: ["Grand Clubhouse", "Forest Walk", "Sports Arena"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 30,
    isPublished: true
  },
  {
    id: "p37",
    slug: "kasturi-balmoral-estate-baner",
    name: "Balmoral Estate",
    builderName: "Kasturi Builders",
    builderScore: 96,
    location: "Baner",
    city: "Pune",
    lat: 18.565,
    lng: 73.788,
    tagline: "The ultimate luxury benchmark",
    description: "Spacious boutique residences for those who value architecture and build quality.",
    trustScore: 96,
    riskLabel: "low",
    reraId: "P52100000124",
    reraExpiry: "2024-03-31",
    launchDate: "2014-01-01",
    possessionDate: "2023-12-31",
    totalUnits: 80,
    availableUnits: 2,
    unitConfigs: [
      {
        id: "u39",
        type: "3BHK",
        area: 1650,
        priceMin: 25000000,
        priceMax: 28000000,
        pricePerSqFt: 15151,
        available: 1,
        total: 40,
        floor: "High",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Designer interiors", "Full height windows"]
      }
    ],
    pros: ["Best build quality in Pune", "Iconic design", "Prime Baner location"],
    cons: ["No fresh supply", "Very expensive"],
    amenities: ["Zen Garden", "Luxury Gym", "Boutique Lobby"],
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p38",
    slug: "majestic-towers-undri",
    name: "Majestic Undri",
    builderName: "Majestic Landmarks",
    builderScore: 76,
    location: "Undri",
    city: "Pune",
    lat: 18.455,
    lng: 73.912,
    tagline: "Spacious living at Undri",
    description: "Large size 2 and 3 BHK apartments for those wanting more space for less money.",
    trustScore: 72,
    riskLabel: "medium",
    reraId: "P52100028742",
    reraExpiry: "2027-12-31",
    launchDate: "2022-01-01",
    possessionDate: "2027-06-30",
    totalUnits: 250,
    availableUnits: 95,
    unitConfigs: [
      {
        id: "u40",
        type: "3BHK",
        area: 1450,
        priceMin: 7800000,
        priceMax: 8800000,
        pricePerSqFt: 5379,
        available: 30,
        total: 100,
        floor: "Any",
        facing: ["Hills"],
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Large balcony", "Hill view"]
      }
    ],
    pros: ["Very spacious", "Quiet surroundings", "Value for money"],
    cons: ["Undri water issue", "Slow developer response"],
    amenities: ["Party Lawn", "Gym", "Kids Area"],
    images: ["https://images.unsplash.com/photo-1449156001437-3a16d1dfda70?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 35,
    isPublished: true
  },
  {
    id: "p39",
    slug: "shree-samarth-villas-sus",
    name: "Samarth Villas Sus",
    builderName: "Samarth Developers",
    builderScore: 72,
    location: "Sus",
    city: "Pune",
    lat: 18.558,
    lng: 73.745,
    tagline: "Independent living near Baner",
    description: "Gated community of independent row houses for families wanting privacy.",
    trustScore: 70,
    riskLabel: "medium",
    reraId: "P52100028965",
    reraExpiry: "2026-12-31",
    launchDate: "2022-06-01",
    possessionDate: "2026-12-31",
    totalUnits: 40,
    availableUnits: 15,
    unitConfigs: [
      {
        id: "u41",
        type: "3BHK Row House",
        area: 1850,
        priceMin: 13500000,
        priceMax: 15500000,
        pricePerSqFt: 7297,
        available: 8,
        total: 40,
        floor: "G+1",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Private Terrace", "Covered Parking"]
      }
    ],
    pros: ["Independent living", "Close to Baner/Hinjewadi", "Gated security"],
    cons: ["Small developer", "Basic amenities", "Sus water issues"],
    amenities: ["Mini Clubhouse", "Garden", "Security"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 55,
    isPublished: true
  },
  {
    id: "p40",
    slug: "kumar-prospera-hadapsar-resale",
    name: "Kumar Prospera (Resale)",
    builderName: "Kumar Properties",
    builderScore: 90,
    location: "Hadapsar",
    city: "Pune",
    lat: 18.511,
    lng: 73.929,
    tagline: "Move in today",
    description: "Exclusive resale opportunity in a premium Kumar project at Hadapsar.",
    trustScore: 94,
    riskLabel: "low",
    reraId: "P52100000459",
    reraExpiry: "2023-12-31",
    launchDate: "2016-01-01",
    possessionDate: "2022-12-31",
    totalUnits: 300,
    availableUnits: 5,
    unitConfigs: [
      {
        id: "u42",
        type: "2BHK",
        area: 1150,
        priceMin: 11500000,
        priceMax: 12500000,
        pricePerSqFt: 10000,
        available: 2,
        total: 150,
        floor: "High",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1460317442991-0ec239f3d6bd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Ready to move", "Prime location"]
      }
    ],
    pros: ["Immediate possession", "Established society", "No construction risk"],
    cons: ["Higher per sqft price", "Resale documentation needed"],
    amenities: ["Clubhouse", "Gym", "Pool"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p41",
    slug: "bramhacorp-f-residences-kalyani-nagar",
    name: "F-Residences",
    builderName: "BramhaCorp",
    builderScore: 87,
    location: "Kalyani Nagar",
    city: "Pune",
    lat: 18.547,
    lng: 73.905,
    tagline: "Live the fashion life",
    description: "Trendsetting fashion-themed residences in the upscale Kalyani Nagar neighborhood.",
    trustScore: 85,
    riskLabel: "low",
    reraId: "P52100000789",
    reraExpiry: "2025-12-31",
    launchDate: "2021-01-01",
    possessionDate: "2025-06-30",
    totalUnits: 350,
    availableUnits: 45,
    unitConfigs: [
      {
        id: "u43",
        type: "3BHK",
        area: 1650,
        priceMin: 22000000,
        priceMax: 25000000,
        pricePerSqFt: 13333,
        available: 15,
        total: 100,
        floor: "Mid",
        facing: ["City View"],
        images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Fashion-inspired interiors", "Home automation"]
      }
    ],
    pros: ["Premium location", "Unique design concept", "High rental demand"],
    cons: ["Higher per sqft price", "Limited visitor parking"],
    amenities: ["Fashion Ramp", "Boutique Pool", "Designer Clubhouse"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 85,
    isPublished: true
  },
  {
    id: "p42",
    slug: "trump-towers-koregaon-park",
    name: "Trump Towers",
    builderName: "Panchshil Realty",
    builderScore: 98,
    location: "Koregaon Park",
    city: "Pune",
    lat: 18.539,
    lng: 73.895,
    tagline: "The most prestigious address in India",
    description: "Two iconic 22-story towers offering unmatched luxury and concierge services.",
    trustScore: 97,
    riskLabel: "low",
    reraId: "P52100000125",
    reraExpiry: "2024-03-31",
    launchDate: "2015-01-01",
    possessionDate: "2023-12-31",
    totalUnits: 44,
    availableUnits: 1,
    unitConfigs: [
      {
        id: "u44",
        type: "5BHK",
        area: 6000,
        priceMin: 150000000,
        priceMax: 180000000,
        pricePerSqFt: 25000,
        available: 1,
        total: 44,
        floor: "High",
        facing: ["City Skyline"],
        images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Private Elevator", "Concierge Service"]
      }
    ],
    pros: ["Global landmark", "Best concierge in Pune", "Highest build quality"],
    cons: ["Extremely high entry price", "High maintenance"],
    amenities: ["Concierge Service", "Outdoor Pool", "Exclusive Club"],
    images: ["https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p43",
    slug: "gera-isle-royale-bavdhan",
    name: "Gera Isle Royale",
    builderName: "Gera Developments",
    builderScore: 95,
    location: "Bavdhan",
    city: "Pune",
    lat: 18.512,
    lng: 73.775,
    tagline: "A royal life in the lap of nature",
    description: "Exclusive estate of independent villas and premium apartments overlooking the hills.",
    trustScore: 94,
    riskLabel: "low",
    reraId: "P52100021459",
    reraExpiry: "2026-06-30",
    launchDate: "2021-01-01",
    possessionDate: "2025-12-31",
    totalUnits: 120,
    availableUnits: 15,
    unitConfigs: [
      {
        id: "u45",
        type: "4BHK Villa",
        area: 4500,
        priceMin: 65000000,
        priceMax: 85000000,
        pricePerSqFt: 14444,
        available: 4,
        total: 30,
        floor: "G+2",
        facing: ["Hills"],
        images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Private Lawn", "Sky Deck"]
      }
    ],
    pros: ["Gera's 5-year warranty", "Scenic hillside location", "High-end community"],
    cons: ["Premium pricing", "Far from eastern IT hubs"],
    amenities: ["Private Pool", "Forest Trail", "Luxury Spa"],
    images: ["https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 75,
    isPublished: true
  },
  {
    id: "p44",
    slug: "rohan-mithila-viman-nagar",
    name: "Rohan Mithila",
    builderName: "Rohan Builders",
    builderScore: 89,
    location: "Viman Nagar",
    city: "Pune",
    lat: 18.567,
    lng: 73.914,
    tagline: "Perfectly designed homes",
    description: "Established premium township in Viman Nagar known for its design and open spaces.",
    trustScore: 91,
    riskLabel: "low",
    reraId: "P52100000460",
    reraExpiry: "2023-12-31",
    launchDate: "2010-01-01",
    possessionDate: "2023-06-30",
    totalUnits: 800,
    availableUnits: 8,
    unitConfigs: [
      {
        id: "u46",
        type: "2BHK",
        area: 1200,
        priceMin: 12000000,
        priceMax: 14000000,
        pricePerSqFt: 10000,
        available: 3,
        total: 200,
        floor: "Mid",
        facing: ["Garden"],
        images: ["https://images.unsplash.com/photo-1460317442991-0ec239f3d6bd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Rohan's 'Plus Home' design", "Cross ventilation"]
      }
    ],
    pros: ["Prime Viman Nagar location", "Extensive open spaces", "Great rental potential"],
    cons: ["Older project", "Resale documentation overhead"],
    amenities: ["Large Central Park", "Multipurpose Court", "Gym"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p45",
    slug: "godrej-forest-grove-mamurdi",
    name: "Forest Grove",
    builderName: "Godrej Properties",
    builderScore: 95,
    location: "Mamurdi",
    city: "Pune",
    lat: 18.665,
    lng: 73.725,
    tagline: "Homes that grow on you",
    description: "Nature-themed residential development near the Mumbai-Pune Expressway.",
    trustScore: 93,
    riskLabel: "low",
    reraId: "P52100021457",
    reraExpiry: "2027-12-31",
    launchDate: "2022-01-01",
    possessionDate: "2027-06-30",
    totalUnits: 1000,
    availableUnits: 250,
    unitConfigs: [
      {
        id: "u47",
        type: "2BHK",
        area: 750,
        priceMin: 5500000,
        priceMax: 6500000,
        pricePerSqFt: 7333,
        available: 120,
        total: 400,
        floor: "Any",
        facing: ["East"],
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Compact and smart", "Expressway views"]
      }
    ],
    pros: ["Trusted Godrej brand", "Great expressway connectivity", "Value for money"],
    cons: ["Far from Pune city", "Limited local infrastructure yet"],
    amenities: ["Tree-top Walk", "Outdoor Gym", "Meditation Zone"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 40,
    isPublished: true
  },
  {
    id: "p46",
    slug: "vtp-pegasus-manjri",
    name: "VTP Pegasus",
    builderName: "VTP Realty",
    builderScore: 91,
    location: "Manjri",
    city: "Pune",
    lat: 18.508,
    lng: 73.975,
    tagline: "New Kharadi's biggest township",
    description: "A 100+ acre township featuring VTP's signature MLA (Maximum Liveable Area) homes.",
    trustScore: 88,
    riskLabel: "low",
    reraId: "P52100028743",
    reraExpiry: "2028-12-31",
    launchDate: "2023-01-01",
    possessionDate: "2028-06-30",
    totalUnits: 2500,
    availableUnits: 450,
    unitConfigs: [
      {
        id: "u48",
        type: "3BHK",
        area: 1150,
        priceMin: 9500000,
        priceMax: 11000000,
        pricePerSqFt: 8260,
        available: 80,
        total: 500,
        floor: "Mid",
        facing: ["River"],
        images: ["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Smart automation", "River view balcony"]
      }
    ],
    pros: ["Massive township infrastructure", "High appreciation potential", "VTP brand reliability"],
    cons: ["Longer wait for possession", "Ongoing construction noise"],
    amenities: ["Grand Clubhouse", "Man-made Lake", "Sports Arena"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 15,
    isPublished: true
  },
  {
    id: "p47",
    slug: "kohinoor-sapphire-tathawade",
    name: "Kohinoor Sapphire",
    builderName: "Kohinoor Group",
    builderScore: 89,
    location: "Tathawade",
    city: "Pune",
    lat: 18.615,
    lng: 73.745,
    tagline: "Connecting you to work and life",
    description: "Strategically located near Hinjewadi and the Expressway, offering budget-friendly homes.",
    trustScore: 90,
    riskLabel: "low",
    reraId: "P52100028744",
    reraExpiry: "2026-12-31",
    launchDate: "2022-01-01",
    possessionDate: "2026-06-30",
    totalUnits: 500,
    availableUnits: 120,
    unitConfigs: [
      {
        id: "u49",
        type: "2BHK",
        area: 850,
        priceMin: 6500000,
        priceMax: 7500000,
        pricePerSqFt: 7647,
        available: 50,
        total: 300,
        floor: "Any",
        facing: ["Garden"],
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Compact design", "Close to colleges"]
      }
    ],
    pros: ["Excellent connectivity", "High rental demand", "Kohinoor brand trust"],
    cons: ["Small open space", "Traffic at Tathawade junction"],
    amenities: ["Mini Pool", "Gym", "Landscaped Garden"],
    images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 55,
    isPublished: true
  },
  {
    id: "p48",
    slug: "pride-purple-park-landmark-baner",
    name: "Park Landmark",
    builderName: "Pride Purple",
    builderScore: 92,
    location: "Baner",
    city: "Pune",
    lat: 18.562,
    lng: 73.782,
    tagline: "Life in a landmark",
    description: "Premium large-sized apartments in a well-established gated community in Baner.",
    trustScore: 91,
    riskLabel: "low",
    reraId: "P52100018746",
    reraExpiry: "2025-12-31",
    launchDate: "2018-01-01",
    possessionDate: "2025-06-30",
    totalUnits: 400,
    availableUnits: 15,
    unitConfigs: [
      {
        id: "u50",
        type: "3BHK",
        area: 1550,
        priceMin: 18000000,
        priceMax: 21000000,
        pricePerSqFt: 11612,
        available: 5,
        total: 100,
        floor: "High",
        facing: ["City View"],
        images: ["https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Large balcony", "Premium finishes"]
      }
    ],
    pros: ["Established community", "Prime Baner location", "High-end amenities"],
    cons: ["Limited availability", "High maintenance"],
    amenities: ["Rooftop Cafe", "Grand Pool", "Sports Zone"],
    images: ["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "under_construction",
    constructionPercent: 95,
    isPublished: true
  },
  {
    id: "p49",
    slug: "paranjape-blue-ridge-the-lofts-hinjewadi",
    name: "The Lofts",
    builderName: "Paranjape Schemes",
    builderScore: 92,
    location: "Hinjewadi",
    city: "Pune",
    lat: 18.578,
    lng: 73.735,
    tagline: "Smart studios for smart people",
    description: "Efficiently designed studio and 1BHK apartments for single professionals and investors.",
    trustScore: 92,
    riskLabel: "low",
    reraId: "P52100000149",
    reraExpiry: "2024-12-31",
    launchDate: "2015-01-01",
    possessionDate: "2024-03-31",
    totalUnits: 200,
    availableUnits: 12,
    unitConfigs: [
      {
        id: "u51",
        type: "Studio",
        area: 450,
        priceMin: 4500000,
        priceMax: 5500000,
        pricePerSqFt: 10000,
        available: 5,
        total: 80,
        floor: "Mid",
        facing: ["Township View"],
        images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Fully furnished option", "Walking distance to IT park"]
      }
    ],
    pros: ["High rental yields", "Low maintenance", "Part of Blue Ridge township"],
    cons: ["Small living space", "Busy township traffic"],
    amenities: ["Laundromat", "Co-working Space", "Rooftop Gym"],
    images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  },
  {
    id: "p50",
    slug: "panchshil-yoo-pune-hadapsar",
    name: "Yoo Pune",
    builderName: "Panchshil Realty",
    builderScore: 98,
    location: "Hadapsar",
    city: "Pune",
    lat: 18.525,
    lng: 73.935,
    tagline: "Designed by Philippe Starck",
    description: "India's first Yoo branded residence, offering designer living and world-class amenities.",
    trustScore: 96,
    riskLabel: "low",
    reraId: "P52100000461",
    reraExpiry: "2023-12-31",
    launchDate: "2012-01-01",
    possessionDate: "2023-12-31",
    totalUnits: 228,
    availableUnits: 4,
    unitConfigs: [
      {
        id: "u52",
        type: "4BHK",
        area: 4500,
        priceMin: 85000000,
        priceMax: 120000000,
        pricePerSqFt: 18888,
        available: 2,
        total: 100,
        floor: "High",
        facing: ["Lush Greens"],
        images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=80&w=800"],
        highlights: ["Designer interiors", "Private lobby"]
      }
    ],
    pros: ["International brand", "Panchshil's superior maintenance", "Unique design aesthetics"],
    cons: ["Very high maintenance cost", "Limited secondary market sales"],
    amenities: ["Spa by Six Senses", "Cigar Lounge", "Heated Pool"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1200"],
    constructionStatus: "ready_to_move",
    constructionPercent: 100,
    isPublished: true
  }
];
